package Telas;
/**
 *
 * @author hebert
 */

import cantinaconectada.Cadastro;
import dados.CadastroDAO;
import java.util.ArrayList;
      
public class TelaRegister extends javax.swing.JFrame{
    
    private TelaLogin tela;
    
    public TelaRegister(TelaLogin tela) {
        initComponents();
        this.tela = tela;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PainelFormulario = new javax.swing.JPanel();
        PainelCampoEmail = new javax.swing.JPanel();
        LabelEmail = new javax.swing.JLabel();
        TextEmail = new javax.swing.JTextField();
        PainelCampoSenha = new javax.swing.JPanel();
        LabelSenha = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        btnSair = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PasswordConfirma = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        TextNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cantina Conectada");
        setMaximumSize(new java.awt.Dimension(380, 330));
        setMinimumSize(new java.awt.Dimension(380, 330));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelPrincipal.setBackground(new java.awt.Color(250, 250, 250));
        PainelPrincipal.setMaximumSize(new java.awt.Dimension(380, 330));
        PainelPrincipal.setMinimumSize(new java.awt.Dimension(380, 330));
        PainelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PainelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Base01.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(380, 128));
        jLabel2.setMinimumSize(new java.awt.Dimension(380, 128));
        jLabel2.setPreferredSize(new java.awt.Dimension(380, 128));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 130, -1));

        PainelFormulario.setMaximumSize(new java.awt.Dimension(200, 150));
        PainelFormulario.setMinimumSize(new java.awt.Dimension(200, 150));
        PainelFormulario.setOpaque(false);
        PainelFormulario.setPreferredSize(new java.awt.Dimension(200, 150));
        PainelFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelCampoEmail.setMaximumSize(new java.awt.Dimension(200, 60));
        PainelCampoEmail.setOpaque(false);
        PainelCampoEmail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelEmail.setText("E-mail Institucional");
        LabelEmail.setMaximumSize(new java.awt.Dimension(200, 25));
        LabelEmail.setMinimumSize(new java.awt.Dimension(200, 25));
        LabelEmail.setPreferredSize(new java.awt.Dimension(200, 25));
        PainelCampoEmail.add(LabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        TextEmail.setMaximumSize(new java.awt.Dimension(200, 35));
        TextEmail.setMinimumSize(new java.awt.Dimension(200, 35));
        TextEmail.setName(""); // NOI18N
        TextEmail.setPreferredSize(new java.awt.Dimension(200, 35));
        PainelCampoEmail.add(TextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, -1, -1));

        PainelFormulario.add(PainelCampoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PainelCampoSenha.setMaximumSize(new java.awt.Dimension(200, 60));
        PainelCampoSenha.setOpaque(false);
        PainelCampoSenha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelSenha.setText("Senha");
        LabelSenha.setMaximumSize(new java.awt.Dimension(200, 25));
        LabelSenha.setMinimumSize(new java.awt.Dimension(200, 25));
        LabelSenha.setPreferredSize(new java.awt.Dimension(200, 25));
        PainelCampoSenha.add(LabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, 20));

        PasswordField.setMaximumSize(new java.awt.Dimension(200, 35));
        PasswordField.setMinimumSize(new java.awt.Dimension(200, 35));
        PasswordField.setPreferredSize(new java.awt.Dimension(200, 35));
        PainelCampoSenha.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 30));

        PainelFormulario.add(PainelCampoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        getContentPane().add(PainelFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 120));

        btnSair.setText("Sair");
        btnSair.setMaximumSize(new java.awt.Dimension(95, 35));
        btnSair.setMinimumSize(new java.awt.Dimension(95, 35));
        btnSair.setPreferredSize(new java.awt.Dimension(95, 35));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 80, -1));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setMaximumSize(new java.awt.Dimension(95, 35));
        btnCadastrar.setMinimumSize(new java.awt.Dimension(95, 35));
        btnCadastrar.setPreferredSize(new java.awt.Dimension(95, 35));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 90, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Confirma Senha");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PasswordConfirma.setMaximumSize(new java.awt.Dimension(200, 35));
        PasswordConfirma.setMinimumSize(new java.awt.Dimension(200, 35));
        PasswordConfirma.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(PasswordConfirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 200, -1));

        jLabel3.setText("Nome");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        TextNome.setMaximumSize(new java.awt.Dimension(200, 35));
        TextNome.setMinimumSize(new java.awt.Dimension(200, 35));
        TextNome.setName(""); // NOI18N
        TextNome.setPreferredSize(new java.awt.Dimension(200, 35));
        getContentPane().add(TextNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String nome = TextNome.getText();
        String email = TextEmail.getText();
        String senha = PasswordField.getText();
        String csenha = PasswordConfirma.getText();
        
        Cadastro c = new Cadastro();
        c.setEmail(email);
        c.setNome(nome);
        c.confirmas(csenha);
        c.setSenha(senha);
        
        CadastroDAO objc = new CadastroDAO();
       objc.cadastroBD(c);
        
        
        ArrayList<Cadastro> cadastro = tela.getLista();
        cadastro.add(c);
        
        tela.setVisible(true);
        this.dispose();
        

    }//GEN-LAST:event_btnCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelSenha;
    private javax.swing.JPanel PainelCampoEmail;
    private javax.swing.JPanel PainelCampoSenha;
    private javax.swing.JPanel PainelFormulario;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JPasswordField PasswordConfirma;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextNome;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
